// <auto-generated />
namespace Tatilcim.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ReservationEdit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReservationEdit));
        
        string IMigrationMetadata.Id
        {
            get { return "201809271108185_ReservationEdit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
